### ISSUE TITLE
How to generate poses with GNINA's CNN [Question]

### ISSUE THREAD

**Issue by mgarort** [gnina/gnina#135]
Dear GNINA team,

I would like to generate poses by minimizing the score of a GNINA's CNN, as described in the paper "Ligand Pose Optimization with Atomic Grid-Based Convolutional Neural Networks" (https://arxiv.org/abs/1710.07400). However, from reading the paper and `gnina --help` it is not clear to me whether it is possible to do it out of the box. It appears that the default pose generation uses Vina under the hood.

Could you please tell me if it is possible to generate poses by minimizing the CNN score with the GNINA version in the binaries, and if so, what options do I need to use? The GNINA version in the binaries is `gnina v1.0 HEAD:6381355   Built Mar  6 2021.`.

Thanks a lot in advance.

**Comment by dkoes** [comment]
Set the cnn scoring mode to refinement with `--cnn_scoring refinement` as described in the README.

**Comment by mgarort** [comment]
Thank you for your swift response @dkoes ! Can I ask to clarify the difference between the `--cnn_scoring` options  `refinement` and `all`?

- `refinement` is described as "CNN used to refine poses after Monte Carlo chains and for final ranking of output poses". Is Autodock Vina used to generate the poses at all before the Monte Carlo chains? Or is this option completely independent of Vina?

- `all` is described as "CNN used as the scoring function throughout the whole procedure". I suppose this option starts with the ligand pose given in the input, and moves this pose iteratively in the direction indicated by the gradient of the CNN score. Is that correct?

Thanks a lot.

**Comment by dkoes** [comment]
I think Figure 1 in this paper makes it pretty clear: https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00522-2

With cnn_scoring=rescore, Vina is used to guide the MC sampling and refine poses, and the CNN does the final scoring and ranking.
With cnn_scoring=refinement, Vina is used to guide the MC sampling and then the CNN takes over for refinement and scoring.
With cnn_scoring=all, the CNN is used throughout, which, since so many scoring evaluations are performed during MC sampling, takes forever.

If you want to optimize a prespecified pose, as opposed to perform a full docking, use `--minimize`.  If cnn_scoring=refinement (or all), the CNN will be used to find the locally optimal pose with respect to the CNN.

**Comment by mgarort** [comment]
That makes sense. Thank you so much for the quick and detailed explanation. Closing the issue now.
