### ISSUE TITLE
Relevance values are extremely large for some residues

### ISSUE THREAD

**Issue by amrhamedp** [gnina/gnina#42]
Some residues can show very high relevance that make the receptor relevance very high .
Example to reproduce:
[184l.zip](https://github.com/gnina/gnina/files/2436350/184l.zip)

[b_factor.zip](https://github.com/gnina/gnina/files/2436351/b_factor.zip)
It is clear that some amino acids which are near the ligand have very high relevance values

**Comment by dkoes** [comment]
I've looked into this and, for better or worse, I don't think there is a bug.  If you generate the grid files with --outputdx, you'll see that the sum of the relevance values adds up to the expected amount even though there are very large individual grid values.

There was a bug with --gpu caused when we added CUDNN acceleration since the CUDNN layers don't do relevance propagation.  I fixed that 70e3f80ca27d193d6998947ce7a862bcdba330a0
