### ISSUE TITLE
'ligand outside box' error

### ISSUE THREAD

**Issue by gregfriedland** [gnina/gnina#48]
### Issue summary

Hello,
I'm evaluating gnina with `--gpu` to see if I can get a speed improvement in docking over smina. My attempts to run gnina in the same way I ran smina are generating errors that don't occur for smina; specifically:
```
MCULE-1000001311 | pose 0 | ligand outside box
MCULE-1000001311 | pose 0 | initial pose not within box
```
Any idea what's going on?
Thanks,
Greg

### Steps to reproduce

```
./gnina --cpu 1 --gpu --receptor protein.mol2 --ligand mols-1.sdf --scoring vina --out gnina.sdf --num_modes 64 --energy_range 99999 --exhaustiveness 4 --autobox_ligand bindingsite.xyz --autobox_add 2 --seed 42
```
[files.zip](https://github.com/gnina/gnina/files/2887917/files.zip)

### Your system configuration
Operating system: Ubuntu 
Compiler: g++ 5.4
CUDA version (if applicable): 9.1
CUDNN version (if applicable): 7.1.2
BLAS: Atlas
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by dkoes** [comment]
That means your box is too small and the ligand doesn't fit inside.  Increase autobox_add.  This would be a problem in smina as well, but smina doesn't have the code to check and generate the warning.

**Comment by gregfriedland** [comment]
Thanks for your quick response. I forgot to include the energies in my last post which surprised me.
For the above gnina command line I got:
```
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
1       3.6        0.000      0.000
2       12.0       2.172      2.511
3       23.6       4.798      5.449
4       26.8       3.541      4.087
5       50.8       2.713      3.141
```

With the same command line (minus the `-gpu` flag), I got:
```
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
1       -6.1       0.000      0.000
2       -5.7       8.507      11.825
3       -5.7       1.213      1.573
4       -5.6       1.493      1.744
5       -5.6       6.061      10.201
```

If I include `-autobox_add` to 5 or 10, the gnina energies go down marginally (lowest is -1.3) and I still get lots of the above errors.

**Comment by Jsunseri** [comment]
a couple of notes:

(1) GPU-assisted docking is not in general faster than the non-GPU version (and is often slower). When we were more actively working on providing this feature, we found that we could get a modest speedup on certain workloads (typically with large compounds or flexible receptor residues) or performing certain subroutines, but on the tasks we typically do there wasn't any benefit. We haven't given up hope that we'll be able to extract a performance gain, but the lack of promise has meant that we haven't been focusing on this feature - and I feel very confident saying that if your interest in using the --gpu option was to use it to do faster docking, don't bother (for the time being). 

(2) since gnina requires the GPU for efficient performance of its primary feature, using convolutional neural networks for molecular modeling, we switched to lower precision floats (smina uses doubles) since arithmetic with those is faster on the GPU. That has led to some issues with the conventional (Vina-like) scoring function, particularly when it's being evaluated on the GPU, since certain arithmetic operations happen in a nondeterministic order there; the non-associativity of floating point arithmetic has meant that we have noticed not only inconsistent results between the CPU and GPU versions, but also inconsistency between multiple runs of the GPU version (and even inconsistency between gnina's and smina's evaluations using the Vina scoring function, though this is less significant and probably solely due to the difference in precision). That said, when I tried to reproduce your issue on my machine, the differences in the GPU results were not quite as extreme:

run0
```
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
1       -4.4       0.000      0.000
2       -4.1       10.020     11.440
3       -3.6       4.161      10.302
4       -3.6       11.332     14.704
5       -3.4       9.164      11.359
```

run1
```
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
1       -4.3       0.000      0.000
2       -3.6       10.778     14.695
3       -3.6       4.568      10.069
4       -3.3       8.861      11.981
5       -3.3       4.522      10.508
```

run2
```mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
1       -4.1       0.000      0.000
2       -4.0       7.335      9.016
3       -3.6       7.441      12.487
4       -3.5       8.461      9.639
5       -3.2       4.293      9.834
```

but the energies are clearly still higher than the CPU version, and I do get a couple of out-of-box warnings. I'm curious what your GPU-docked poses look like - can you attach them? Are they way out of the pocket? Do you consistently get energies similar to what you've shown when you run several times? It'd be nice if this example consistently gives you these poor poses and if I could reproduce that, since it would be very helpful for identifying any relevant bug. 

At this point I'm interested in figuring out whether the discrepancy here is due to a legitimate bug or part of this lingering numerical issue, and also why you seem to be getting significantly worse poses than I am. What GPU are you running on?

**Comment by gregfriedland** [comment]
Thanks for your detailed explanations. That's helpful to know you don't expect much speed improvement over smina; I'll stop digging in that direction then. :)

That's interesting you're getting much better energies with the same inputs. Those energies in fact are reproducible for me. I've attached my pose outputs. They're not outside the box but they are making some obvious clashes with the protein.
[gnina.sdf.zip](https://github.com/gnina/gnina/files/2892972/gnina.sdf.zip)

My GPU is an Nvidia K80 (running on an AWS p2.xlarge) with CUDA driver version 410.48 and CUDA 9.1. Happy to help further.
