### ISSUE TITLE
Confusions of GPU and CNN usage

### ISSUE THREAD

**Issue by wquc** [gnina/gnina#99]
**1. Does gnina use GPU for docking?**

When I tried the following
```
gnina -r receptor.pdbqt -l lig.pdbqt --autobox_ligand lig.pdbqt --autobox_add 8 --exhaustiveness 16 -o result.pdbqt --cnn --gpu
```
The GPU utility is 0 (monitored by nvidia-smi) until the following progress bar finishes:
```
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
```
Then gnina uses GPU but the program ends very quickly (<1s) after the following printed out.

```

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
1       -11.2      0.000      0.000
2       -9.6       2.448      3.302
3       -9.4       1.964      2.617
4       -9.2       4.300      7.475
5       -9.2       2.123      2.584
6       -8.9       3.152      7.097
7       -8.8       3.155      7.199
8       -8.7       4.405      6.985
9       -8.7       3.046      3.804
Refine time 27.397
Loop time 30.817
```

**2. What is happening when only `--gpu` is specified**, i.e. the following command:
```
gnina -r receptor.pdbqt -l lig.pdbqt --autobox_ligand lig.pdbqt --autobox_add 8 --exhaustiveness 16 -o result.pdbqt --gpu
```

The GPU utility is 99% but the program is running extremely slow (~50 times slower than above example) and the result is also weird:
```

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box
 | pose 0 | ligand outside box

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
1       -4.8       0.000      0.000
2       -3.4       7.630      11.349
3       -2.9       4.199      5.878
4       -2.7       7.029      9.203
5       -2.4       6.462      9.368
6       -2.1       6.103      8.684
Refine time 1440.356
Loop time 1450.621

```

**3. What is the difference between `--cnn` and `--cnn_model`** ?
Both seem to be related to default model, and specifying both with empty argument, i.e. `--cnn --cnn_model --gpu` will result in same slow performance as Question 2.

**4. Does gnina support multi GPU?**
I've tried `--device 0,1 --gpu` but it doesn't recognize the command.

**Comment by Jsunseri** [comment]
1. We don't currently recommend passing `--gpu` unless you're using the CNN for evaluations. The arguments that are **required** to use a CNN are `--cnn_scoring` or `--cnn_refinement`; passing `--cnn` with no model name will result in an error if you pass either of those, but it doesn't in your example input because the CNN isn't actually being used (because neither `--cnn_scoring` nor `--cnn_refinement` were passed). 
We have mostly done evaluations of using the CNN to rescore (`--score_only`) and minimize (`--minimize`) poses; if you want to evaluate docking exclusively with the CNN, you'll likely need to reduce the number of MC steps (`--num_mc_steps`) and/or the exhaustiveness (`--exhaustiveness`). To fix your example input to get CNN docking, just change `--cnn` to `--cnn_scoring`; that'll probably be slow, so if you're just trying to see how it works you can set e.g. `--num_mc_steps 10` to speed up the evaluation. That said, we **recommend** using a conventional scoring function (e.g. what you get if you don't pass `--cnn_scoring` **or** `--gpu`) to dock and then just using `--cnn_scoring` with `--score_only` or `--minimize`. 

2. This example is actually docking with a conventional scoring function (**not** the CNN) on the GPU, but that's currently a work in progress and we don't recommend using it. We haven't worked on this feature for a while so code rot could be at play here, but in the past there were issues with gradients not converging leading to far more evaluations happening when using the GPU for docking. 

3. We provide several built-in models with pretrained weights. These can be accessed by name via `--cnn`. You can pass gnina your own model file (in `prototxt` format) via `--cnn_model`; in that case, you will also need to pass in weights with `--cnn_weights`. If you check the argument descriptions with `--help`, you'll see the model options for `--cnn`: 
```
  --cnn arg                        built-in model to use: crossdock_default2018
                                   crossdock_default2018_1
                                   crossdock_default2018_2
                                   crossdock_default2018_3
                                   crossdock_default2018_4 default2017 dense
                                   dense_1 dense_2 dense_3 dense_4
                                   general_default2018 general_default2018_1
                                   general_default2018_2 general_default2018_3
                                   general_default2018_4
```
so e.g. you could pass `--cnn_scoring --cnn dense` to perform scoring using one of the ensemble of pretrained dense nets we've provided. 

4. No. gnina uses Caffe for CNN evaluations, and Caffe doesn't support multi-GPU usage for test-phase evaluations (see e.g. https://github.com/BVLC/caffe/blob/master/docs/multigpu.md).
